- hosts: windows
  connection: winrm
  tasks:
    - name: "Simulate connection failure"
      lineinfile:
        path: "C:\\Windows\\System32\\drivers\\etc\\hosts"
        line: "127.0.0.1 bit.ly"
      tags:
      - service_down
        
    - name: "Restore service"
      lineinfile:
        path: "C:\\Windows\\System32\\drivers\\etc\\hosts"
        line: "127.0.0.1 bit.ly"
        state: absent
      tags:
      - service_up
