---
- name: Install IIS and configure website
  hosts: all
  vars:
      ansible_user: administrator
      ansible_password: JustM300
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
      ansible_winrm_server_cert_validation: ignore
      ip_address: 10.0.0.1
      database_name: mydatabase
      db_username: sqluser
      db_password: Pa$$w0rd
  roles:
    - create-user
    - install-iis
    - create-web-config