---
- name: Ensure IIS is installed and started 
  hosts: webservers
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_user: Administrator
    ansible_password: JustM300
    service_name: IIS Admin Service   
  tasks:
    - name: Ensure IIS Server is present 
      win_feature:
        name:  Web-Server
        state: present
        restart: no
        include_sub_features: yes
        include_management_tools: yes  
    - name: Ensure latest web files are present
      win_copy:
        src: playbook-fun/files/
        dest: c:\inetpub\wwwroot\
        force: yes
    - name: Ensure IIS is started
   
      win_service:
        name: "{{ service_name }}"
        state: started